server:
  port: 9098
spring:
  profiles.active: local
  application:
    name: app-service-one   #current service name to be used by the eureka server
  
  liquibase:
    enabled: false
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
     
#management:
 # security:
    #enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc. 
 
logging:
  level:
    com.application: DEBUG